### ISSUE TITLE
Prepare HighAvailabilityPgConnectionImpl for using as a long-live singleton (spring bean)

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health#121]
HighAvailabilityPgConnectionImpl needs to be a long-live singleton for using as a spring bean in spring boot starter.
In this case we cannot determe primary host in constructor and remember it because in real PostgreSQL cluster primary host may change its location due to failover or switchover.

This issue is linked with https://github.com/mfvanek/pg-index-health-spring-boot-demo/issues/11

**Comment by Evreke** [comment]
I'd like to work on it. Could you assign issue to me?

**Comment by mfvanek** [comment]
@Evreke
Yes, sure. Feel free to contribute

**Comment by mfvanek** [comment]
@Evreke 
Thanks a lot! I really appreciate your work!
