### ISSUE TITLE
Consider to add Forbidden API Checker

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health#195]
Add Forbidden API Checker instead of IllegalMethodCall from checkstyle
https://github.com/policeman-tools/forbidden-apis
https://plugins.gradle.org/plugin/de.thetaphi.forbiddenapis

**Comment by mfvanek** [comment]
Example of usage https://github.com/pgjdbc/pgjdbc/blob/master/config/forbidden-apis/forbidden-apis.txt

**Comment by BLoHny** [comment]
Can i try it?

**Comment by mfvanek** [comment]
> Can i try it?

@BLoHny yes, sure

**Comment by BLoHny** [comment]
Should I configure Forbidden Check to root or just the pg-index-health module?

**Comment by mfvanek** [comment]
> Should I configure Forbidden Check to root or just the pg-index-health module?

It should be applied to root and should work for all subprojects

**Comment by mfvanek** [comment]
@BLoHny
Could you add these checks to the https://github.com/mfvanek/pg-index-health-demo as well?
