### ISSUE TITLE
Add check "Don't use serial"

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health#317]
See

- https://stackoverflow.com/questions/55300370/postgresql-serial-vs-identity
- https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_serial

**Comment by manumafe98** [comment]
Hi @mfvanek I would like to work on this one!

**Comment by mfvanek** [comment]
Hi @manumafe98 !
Sure! Feel free to contribute

**Comment by manumafe98** [comment]
Thanks @mfvanek! I'm needing a bit more information on this one, the goal is to make a test that checks that ``serial`` is not being used?

**Comment by mfvanek** [comment]
@manumafe98 
The goal is to help developers to migrate to new syntax while defining primary keys. Instead of old smallserial/serial/bigserial new "generated as identity" syntax should be used.  

You need to implement a new sql query to find cases of using old syntax. As example you can use https://github.com/mfvanek/pg-index-health-sql/blob/master/sql/non_primary_key_columns_with_serial_types.sql 

Then you need to implement a Java layer above new sql query. A new class have to appear in https://github.com/mfvanek/pg-index-health/tree/master/pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host. See https://github.com/mfvanek/pg-index-health/blob/master/pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host/ColumnsWithSerialTypesCheckOnHost.java as example

**Comment by mfvanek** [comment]
Hi @manumafe98 
Any updates?

**Comment by manumafe98** [comment]
Hey @mfvanek I'm going to unassign it, currently i'm a bit swamped and I think there is a lot that i should learn to make progress on this issue currently, thanks for the information, maybe I will give it a try in the future if it still open!

**Comment by mfaulther** [comment]
Hi @mfvanek 
May i take this issue ?

**Comment by mfvanek** [comment]
> Hi @mfvanek May i take this issue ?

Yes, sure! I appreciate your help.

**Comment by mfaulther** [comment]
Hi, @mvfanek

Found some problems with naming here
There is already a check named 'ColumnsWithSerialTypesCheckOnHost' in project that
checks for columns of serial types that are not primary keys.
I see 2 options here:
1. Name new check something other like `SerialColumnsCheckOnHost`, but then it could be confused with existing check - `ColumnsWithSerialTypesCheckOnHost`
2. Rename existing check `ColumnsWithSerialTypesCheckOnHost` with something like `NonPrimaryKeyColumnsWithSerialTypesCheckOnHost`

**Comment by mfvanek** [comment]
@mfaulther 
What if we call it a `PrimaryKeysWithSerialTypesCheckOnHost`?
We will check only primary keys for simplicity.
The main idea here is to popularize the new syntax (`GENERATED AS IDENTITY`).

**Comment by mfaulther** [comment]
Ok, thanks, sounds good
I'll take `PrimaryKeysWithSerialTypesCheckOnHost`

**Comment by mfvanek** [comment]
@mfaulther 
Hi! How are you doing?
Do you plan to finish this issue?

**Comment by mfaulther** [comment]
@mfvanek 
Hi !
Yes, i'm planning to finish this issue. Sorry for delay. I've created PR

**Comment by mfvanek** [comment]
@mfaulther please add example to the demo app as well

**Comment by mfaulther** [comment]
> @mfaulther please add example to the demo app as well

Ok, i'll add example to [https://github.com/mfvanek/pg-index-health-demo](https://github.com/mfvanek/pg-index-health-demo), when new version (`1.12.1`) of pg-index-health comes out

**Comment by mfvanek** [comment]
> Ok, sure. I'll add example to [pg-index-health-demo](https://github.com/mfvanek/pg-index-health-demo), when new version of pg-index-health (`0.12.1`) comes out

@mfaulther 
I've released a new version **0.13.0**.
Now you can update demo apps
