### ISSUE TITLE
Add check "Do not index booleans"

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health#322]
Extracted from https://github.com/mfvanek/pg-index-health/issues/45

See the article by Kirill Borovikov posted on Habr https://habr.com/ru/companies/tensor/articles/488104/   
Part "Bad: too little (boolean)". 

1. Add new sql-query to https://github.com/mfvanek/pg-index-health-sql  
2. Then implement new check with tests
3. After that add example to demo apps

**Comment by Evreke** [comment]
Here is prototype of request that select indexes with boolean type in it.

```sql
select -- pn.nspname,
       pi.indrelid::regclass::text   as table_name,
       pi.indexrelid::regclass::text as index_name,
       col.attname                   as column_name
       -- col.atttypid::regtype::text   as column_type
from pg_catalog.pg_index pi
         join pg_catalog.pg_class pc on pc.oid = pi.indexrelid
         join pg_catalog.pg_namespace pn on pn.oid = pc.relnamespace
         join pg_catalog.pg_attribute col on col.attrelid = pi.indrelid and col.attnum = any (pi.indkey)
where pn.nspname = 'public'::text
  and NOT pi.indisunique
  AND pi.indisready
  AND pi.indisvalid
  AND col.atttypid = 'boolean'::regtype
order by table_name, index_name;
```

**Comment by Evreke** [comment]
Going to implement feature this week. Sorry for delay.

**Comment by mfvanek** [comment]
Need to

- [ ] update readme
- [ ] add sample to the demo apps
