### ISSUE TITLE
Add overloaded methods to create tables/indexes without specifying zero size

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health#526]
In tests often used
```
Table.of("application", 0L)
```

**Comment by gmottajr** [comment]
Hi @mfvanek ,
I'd like to help with this issue. Could you please provide more details about the specific challenges you're facing?
What/where is the fix to be done?
Acceptance criteria, and details about the unit test wanted? 
 I'll be happy to assist in improving the implementation.

**Comment by mfvanek** [comment]
@gmottajr you'd better to start with any issue labeled as [good first issue](https://github.com/mfvanek/pg-index-health/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
