### ISSUE TITLE
Add examples how to use in tests to README

### ISSUE THREAD

**Issue by SButterfly** [mfvanek/pg-index-health#65]
Hello, could you add examples of using your library at unit/functional tests to readme?

**Comment by mfvanek** [comment]
> Hello, could you add examples of using your library at unit/functional tests to readme?

Hi Sergey,
Thank you for your feedback.

There is a demo project with example of using pg-index-health in unit tests. Take a look at  https://github.com/mfvanek/pg-index-health-demo/blob/master/src/test/java/io/github/mfvanek/pg/index/health/demo/IndexesMaintenanceTest.java

I'll add this information to readme.
