### ISSUE TITLE
Wrong detection of Duplicated indexes

### ISSUE THREAD

**Issue by SButterfly** [mfvanek/pg-index-health#76]
```sql
create table t
(
    id   bigserial primary key,
    text text not null
);
create index ix_text on t (text);
create index ix_text_collate on t (text COLLATE "C.UTF-8");
```

**Comment by mfvanek** [comment]
@SButterfly
I don't think that it's a bug. It's a strange to use collation while creating index. It looks like in this case using of text_pattern_ops would be more preferable.
Could you please provide more information about your use case?

**Comment by mfvanek** [comment]
Linked issue #61

**Comment by SButterfly** [comment]
> Could you please provide more information about your use case?

We use index_with_collate  for such queries:
`select * from table whete (text collate "C.UTF-8") = ?;`
Also we use ilike search
`select * from table whete (text collate "C.UTF-8") ilike '%pattern%';`

**Comment by mfvanek** [comment]
how to repro
`CREATE COLLATION "C.UTF-8" FROM "en-US-x-icu";`
https://dba.stackexchange.com/questions/240930/postgresql-difference-between-collations-c-and-c-utf-8
https://simply.name/ru/pg-lc-collate.html
